# Generated by Django 3.2.5 on 2021-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUR', 'Ruble')], max_length=4)),
                ('source', models.CharField(default='privatbank', max_length=20)),
                ('buy_price', models.DecimalField(decimal_places=5, max_digits=19)),
                ('sell_price', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
        ),
    ]
